import {AfterViewInit, Component} from '@angular/core';
import {
  MatCell,
  MatCellDef,
  MatColumnDef,
  MatHeaderCell, MatHeaderCellDef,
  MatHeaderRow,
  MatHeaderRowDef,
  MatRow, MatRowDef, MatTable
} from "@angular/material/table";
import {MatSort} from "@angular/material/sort";
import {Match} from "../../model/match";

@Component({
  selector: 'app-match-table',
  standalone: true,
  imports: [
    MatCell,
    MatCellDef,
    MatColumnDef,
    MatHeaderCell,
    MatHeaderRow,
    MatHeaderRowDef,
    MatRow,
    MatRowDef,
    MatSort,
    MatTable,
    MatHeaderCellDef
  ],
  templateUrl: './match-table.component.html',
  styleUrl: './match-table.component.css'
})
export class MatchTableComponent implements AfterViewInit {
  displayedColumns: string[] = ['student', 'org', 'donor', 'address', 'donation'];
  matches: Match[] = [];

  constructor() { }

  ngAfterViewInit(): void {
    this.matches = [
      {id: 1, studentName: 'Daphne Vasilakis', studentSection: 'Red', studentGroup: 'A', donorOrg: '', donorName: 'Nyree Hidalgo', donorAddress: '142 Main Street Goshen, NY 10924', donation: '225'},
      {id: 2, studentName: 'Daphne Vasilakis', studentSection: 'Red', studentGroup: 'A', donorOrg: 'Persico True Value', donorName: 'Gao Shen', donorAddress: 'PO Box 1118 Pine Bush, NY 12566', donation: '112.5'},
      {id: 3, studentName: 'Eleanor Mezzanini', studentSection: 'Red', studentGroup: 'A', donorOrg: '', donorName: '', donorAddress: '21 Ramsey Place Albany, NY 12208', donation: 'A Facilitator'},
      {id: 4, studentName: 'Eleanor Mezzanini', studentSection: 'Red', studentGroup: 'A', donorOrg: '', donorName: '', donorAddress: '33 west rand street ilion, NY 13357', donation: '225'},
      {id: 5, studentName: 'Helen LeStage', studentSection: 'Red', studentGroup: 'A', donorOrg: 'Pine Bush Lions Club', donorName: 'Daniel Paddock', donorAddress: '13 Lark Street Greenwich, NY 12834', donation: '100'},
      {id: 6, studentName: 'Helen LeStage', studentSection: 'Red', studentGroup: 'A', donorOrg: 'Revitalization Committee of BG 137', donorName: '', donorAddress: '109 S Comrie Ave Johnstown, NY 12095', donation: 'Red Section Leader'},
      {id: 7, studentName: 'Jennifer Patino', studentSection: 'Red', studentGroup: 'A', donorOrg: '', donorName: '', donorAddress: '1219 5th Ave. Watervliet, NY 12189', donation: '225'},
      {id: 8, studentName: 'Jennifer Patino', studentSection: 'Red', studentGroup: 'A', donorOrg: 'Greenwich Lions Club', donorName: 'John Swartwout', donorAddress: '725 Madison Avenue Albany, NY 12208', donation: '225'},
      {id: 9, studentName: 'Luke Giglio', studentSection: 'Red', studentGroup: 'A', donorOrg: 'Loyal Order of Moose #1185', donorName: '', donorAddress: '2880 Curry Rd Schenectady, NY 12303', donation: 'Red Section Leader'},
      {id: 10, studentName: 'Luke Giglio', studentSection: 'Red', studentGroup: 'A', donorOrg: '', donorName: '', donorAddress: '1219 5th Ave. Watervliet, NY 12189', donation: 'Ice Cream'},
      {id: 11, studentName: 'Lydia Pekrul', studentSection: 'Red', studentGroup: 'A', donorOrg: 'The Women\'s Club of Albany', donorName: 'John Swartwout', donorAddress: '', donation: 'A Facilitator'},
      {id: 12, studentName: 'Lydia Pekrul', studentSection: 'Red', studentGroup: 'A', donorOrg: 'Long Energy', donorName: '', donorAddress: '33 west rand street ilion, NY 13357', donation: 'back packs, floss, water bottles'},
      {id: 13, studentName: 'Sonia Chaugule', studentSection: 'Red', studentGroup: 'A', donorOrg: '', donorName: 'Daniel Paddock', donorAddress: '', donation: '500'},
      {id: 14, studentName: 'Sonia Chaugule', studentSection: 'Red', studentGroup: 'A', donorOrg: 'Stewarts', donorName: '', donorAddress: '3-7 Reed Street Coxsackie, NY 12051', donation: '225'},
      {id: 15, studentName: 'Yasmin Issa', studentSection: 'Red', studentGroup: 'A', donorOrg: '', donorName: 'Nicole Bliess', donorAddress: '9 Patroon Place Glen Mont, NY 12077-3622', donation: '200'},
      {id: 16, studentName: 'Yasmin Issa', studentSection: 'Red', studentGroup: 'A', donorOrg: 'Antham', donorName: 'Karen Pass', donorAddress: '241 Bishopville Loop The Villages, FL 32162', donation: 'Speaker'},
      {id: 17, studentName: 'Grace Bedinotti', studentSection: 'Red', studentGroup: 'B', donorOrg: 'NB Coxsackie', donorName: 'Linda Davis', donorAddress: '22 Corporate Woods Blvd, Suite 501 Albany, NY 12211', donation: '500'},
      {id: 18, studentName: 'Grace Bedinotti', studentSection: 'Red', studentGroup: 'B', donorOrg: '', donorName: 'Mara Afzail', donorAddress: '180 Schwenk Drive Kingston, NY 12401', donation: '225'},
      {id: 19, studentName: 'Jasper Burdo', studentSection: 'Red', studentGroup: 'B', donorOrg: '', donorName: 'Lynne White', donorAddress: '9 Patroon Place Glen Mont, NY 12077-3622', donation: 'B Facilitator'},
      {id: 20, studentName: 'Jasper Burdo', studentSection: 'Red', studentGroup: 'B', donorOrg: '', donorName: 'Karen Pass', donorAddress: '1412 Richmond RD Santa Paula, CA 93060', donation: '225'},
      {id: 21, studentName: 'Jonathan Gonzaga', studentSection: 'Red', studentGroup: 'B', donorOrg: 'Ulster Savings Bank', donorName: 'Jessenia Montiel', donorAddress: '1226 State Route 86 Saranac Lake, NY 12983', donation: 'B Facilitator'},
      {id: 22, studentName: 'Jonathan Gonzaga', studentSection: 'Red', studentGroup: 'B', donorOrg: '', donorName: '', donorAddress: '1412 Richmond RD Santa Paula, CA 93060', donation: '225'},
      {id: 23, studentName: 'Michael Silva', studentSection: 'Red', studentGroup: 'B', donorOrg: '', donorName: 'Jessenia Montiel', donorAddress: '9 Patroon Place Glen Mont, NY 12077-3622', donation: '500'},
      {id: 24, studentName: 'Michael Silva', studentSection: 'Red', studentGroup: 'B', donorOrg: 'Restwork LLC', donorName: 'Karen Pass', donorAddress: '180 Schwenk Drive Kingston, NY 12401', donation: '225'},
      {id: 25, studentName: 'Nolan Boyles', studentSection: 'Red', studentGroup: 'B', donorOrg: '', donorName: 'Lynne White', donorAddress: '88 Main Street Ravena, NY 12143-1711', donation: '100'},
      {id: 26, studentName: 'Nolan Boyles', studentSection: 'Red', studentGroup: 'B', donorOrg: '', donorName: '', donorAddress: '', donation: 'Speaker'},
      {id: 27, studentName: 'Tiyhna Asson', studentSection: 'Red', studentGroup: 'B', donorOrg: 'Ulster Savings Bank', donorName: '', donorAddress: '480 Broadway Saratoga Springs, NY 12866', donation: 'Speaker'},
      {id: 28, studentName: 'Tiyhna Asson', studentSection: 'Red', studentGroup: 'B', donorOrg: 'Mueller\'s Automitive LLC', donorName: 'Marcella Hammer', donorAddress: '141 Washington Ave Albany, NY 12210', donation: '250'},
      {id: 29, studentName: 'Za\'niah Welch', studentSection: 'Red', studentGroup: 'B', donorOrg: 'Glove Cities Rotary Club', donorName: 'Jahkeen Hoke', donorAddress: '104 River Street Sidney, NY 13838', donation: '103.19'},
      {id: 30, studentName: 'Za\'niah Welch', studentSection: 'Red', studentGroup: 'B', donorOrg: '', donorName: '', donorAddress: '12 Whitman Ct Troy, NY 12180', donation: 'Speaker'},
      {id: 31, studentName: 'Za\'niah Welch', studentSection: 'Red', studentGroup: 'B', donorOrg: '', donorName: 'Cara Sherwood', donorAddress: '', donation: 'B J-Staff'},
      {id: 32, studentName: 'Ava Brown', studentSection: 'Red', studentGroup: 'C', donorOrg: 'Sidney Lodge No 2175 BPOE Inc', donorName: 'Walter Thorne', donorAddress: '393 Old Loomis Rd Liberty, NY 12754', donation: '50'},
      {id: 33, studentName: 'Ava Brown', studentSection: 'Red', studentGroup: 'C', donorOrg: '', donorName: 'Rachel Yaun', donorAddress: '144 Harrison Street Johnstown, NY 12095', donation: '225'},
      {id: 34, studentName: 'Ava Brown', studentSection: 'Red', studentGroup: 'C', donorOrg: '', donorName: '', donorAddress: 'PO Box 514 Kinderhook, NY 12106', donation: '225'},
      {id: 35, studentName: 'Bridghid Reeve', studentSection: 'Red', studentGroup: 'C', donorOrg: '', donorName: '', donorAddress: '393 Old Loomis Rd Liberty, NY 12754', donation: 'C Facilitator'},
      {id: 36, studentName: 'Bridghid Reeve', studentSection: 'Red', studentGroup: 'C', donorOrg: 'Asante Sign Group', donorName: 'Carl Yaun', donorAddress: '5648 Lake Shore Dr Bolton Landing, NY 12814', donation: 'Tolietries'},
      {id: 37, studentName: 'Ellery Pierce', studentSection: 'Red', studentGroup: 'C', donorOrg: 'Kinderhook Elks Lodge #2530', donorName: 'Madeline DeLorenzo', donorAddress: '', donation: 'C Facilitator'},
      {id: 38, studentName: 'Ellery Pierce', studentSection: 'Red', studentGroup: 'C', donorOrg: '', donorName: '', donorAddress: '5648 Lake Shore Dr Bolton Landing, NY 12814', donation: '225'},
      {id: 39, studentName: 'Emma Schmidt', studentSection: 'Red', studentGroup: 'C', donorOrg: '', donorName: 'Madeline DeLorenzo', donorAddress: '88 Main Street Ravena, NY 12143-1711', donation: '225'},
      {id: 40, studentName: 'Emma Schmidt', studentSection: 'Red', studentGroup: 'C', donorOrg: 'OraLine', donorName: '', donorAddress: 'PO Box 141 Delmar, NY 12054', donation: '225'},
      {id: 41, studentName: 'Maille Kelley', studentSection: 'Red', studentGroup: 'C', donorOrg: '', donorName: '', donorAddress: '88 Main Street Ravena, NY 12143-1711', donation: '500'},
      {id: 42, studentName: 'Maille Kelley', studentSection: 'Red', studentGroup: 'C', donorOrg: 'Mueller\'s Automitive LLC', donorName: '', donorAddress: '24 Green Ave Cooperstown, NY 13326', donation: '103.19'},
      {id: 43, studentName: 'Marcello Merced', studentSection: 'Red', studentGroup: 'C', donorOrg: 'Bethlehem Lions Club', donorName: 'Matthew Marcotk', donorAddress: '', donation: '225'},
      {id: 44, studentName: 'Marcello Merced', studentSection: 'Red', studentGroup: 'C', donorOrg: 'Mueller\'s Automitive LLC', donorName: 'Betsy Tromans', donorAddress: 'PO Box 514 Kinderhook, NY 12106', donation: '225'},
      {id: 45, studentName: 'Rue Quarters', studentSection: 'Red', studentGroup: 'C', donorOrg: 'Leatherstocking Region FCU', donorName: '', donorAddress: '111 Main Ave Wynantskill, NY 12198', donation: '225'},
      {id: 46, studentName: 'Rue Quarters', studentSection: 'Red', studentGroup: 'C', donorOrg: '', donorName: '', donorAddress: '1241 State Street Schenectady, NY 12304', donation: '225'},
      {id: 47, studentName: 'Anastacia Ferrando', studentSection: 'Orange', studentGroup: 'D', donorOrg: 'Kinderhook Elks Lodge #2530', donorName: '', donorAddress: '32 Luzerene Rd Queensbury, NY 12804', donation: '225'},
      {id: 48, studentName: 'Anastacia Ferrando', studentSection: 'Orange', studentGroup: 'D', donorOrg: 'American Legion Post 1489', donorName: '', donorAddress: 'PO Box 84 Cambridge, NY 12816', donation: '25'},
      {id: 49, studentName: 'Aubrey Wood', studentSection: 'Orange', studentGroup: 'D', donorOrg: 'Veterans of Foreign Wars Schenectady Post 357', donorName: '', donorAddress: '2441 US Route 9W Ravena, NY 12143', donation: '225'},
      {id: 50, studentName: 'Aubrey Wood', studentSection: 'Orange', studentGroup: 'D', donorOrg: 'Queensbury VFW Post 6196', donorName: '', donorAddress: 'PO Box 158 Luke Luzerne, NY 12846', donation: 'D Facilitator'},
      {id: 51, studentName: 'Brexyss Gerow', studentSection: 'Orange', studentGroup: 'D', donorOrg: 'Cpt Maxson Post #634', donorName: '', donorAddress: '1877 Ridge Road Webster, NY 14580', donation: '225'},
      {id: 52, studentName: 'Brexyss Gerow', studentSection: 'Orange', studentGroup: 'D', donorOrg: 'Shear Creations Studio', donorName: 'Madelyn Lehmann', donorAddress: '2880 Curry Rd Schenectady, NY 12303', donation: 'Orange Section Leader'},
      {id: 53, studentName: 'Jackson Miller', studentSection: 'Orange', studentGroup: 'D', donorOrg: 'Hadley Luzerne Lions Club', donorName: '', donorAddress: '80 Halls Hill Road, B Colchester, CT  6415', donation: '25'},
      {id: 54, studentName: 'Mary Mahoney', studentSection: 'Orange', studentGroup: 'D', donorOrg: '', donorName: 'Carly Piché', donorAddress: '99 Main St Ravena, NY 12143', donation: '225'},
      {id: 55, studentName: 'Mary Mahoney', studentSection: 'Orange', studentGroup: 'D', donorOrg: 'Long Energy', donorName: '', donorAddress: '111 Main Ave Wynantskill, NY 12198', donation: '25'},
      {id: 56, studentName: 'Mia Newsom', studentSection: 'Orange', studentGroup: 'D', donorOrg: '', donorName: '', donorAddress: '2441 US Route 9W Ravena, NY 12143', donation: 'D Facilitator'},
      {id: 57, studentName: 'Mia Newsom', studentSection: 'Orange', studentGroup: 'D', donorOrg: 'Persico True Value', donorName: '', donorAddress: '1877 Ridge Road Webster, NY 14580', donation: '225'},
      {id: 58, studentName: 'Natalie Krisanda', studentSection: 'Orange', studentGroup: 'D', donorOrg: 'American Legion Post 1489', donorName: 'Madelyn Lehmann', donorAddress: '242 Poplar Ave Valley Falls, NY 12185', donation: '225'},
      {id: 59, studentName: 'Natalie Krisanda', studentSection: 'Orange', studentGroup: 'D', donorOrg: 'Shear Creations Studio', donorName: '', donorAddress: 'PO Box 528 Glens Falls, NY 12801', donation: '200'},
      {id: 60, studentName: 'Phillip Gargiulo', studentSection: 'Orange', studentGroup: 'D', donorOrg: '', donorName: '', donorAddress: '4 High  Ridge Road New Platz, NY 12561', donation: '50'},
      {id: 61, studentName: 'Phillip Gargiulo', studentSection: 'Orange', studentGroup: 'D', donorOrg: 'Chester James Carknard Post No 1938', donorName: '', donorAddress: '134 Cedar grove Rd Selkirk, NY 12158', donation: '500'},
      {id: 62, studentName: 'Ryan Greenstein', studentSection: 'Orange', studentGroup: 'D', donorOrg: 'Glens Falls Lions', donorName: 'Patricia Grogan', donorAddress: '3-7 Reed Street Coxsackie, NY 12051', donation: '103.19'},
      {id: 63, studentName: 'Sigourney-Page Kinzonzi', studentSection: 'Orange', studentGroup: 'D', donorOrg: 'Poughkeepsie Kiwanis Club', donorName: 'Nicole Bliess', donorAddress: '', donation: 'Speaker'},
      {id: 64, studentName: 'Sigourney-Page Kinzonzi', studentSection: 'Orange', studentGroup: 'D', donorOrg: '', donorName: 'Betsy Tromans', donorAddress: '1 Steuben Place Albany, NY 12207', donation: 'Orange Section Leader'},
      {id: 65, studentName: 'Ahmed Merdanovic', studentSection: 'Orange', studentGroup: 'E', donorOrg: 'NB Coxsackie', donorName: 'Angelique Powell', donorAddress: '80 Halls Hill Road, B Colchester, CT  6415', donation: '200'},
      {id: 66, studentName: 'Ahmed Merdanovic', studentSection: 'Orange', studentGroup: 'E', donorOrg: '', donorName: 'Carly Piché', donorAddress: 'PO Box 165 Peru, NY 12972', donation: 'P J-Staff'},
      {id: 67, studentName: 'Ahmed Merdanovic', studentSection: 'Orange', studentGroup: 'E', donorOrg: '', donorName: '', donorAddress: '1226 state Route 86 Saranac Lake, NY 12983', donation: 'Tolietries'},
      {id: 68, studentName: 'Anna Marquissee', studentSection: 'Orange', studentGroup: 'E', donorOrg: '', donorName: 'Addison Ash', donorAddress: '', donation: 'Orange Section Leader'},
      {id: 69, studentName: 'Anna Marquissee', studentSection: 'Orange', studentGroup: 'E', donorOrg: 'Peru Lions Club', donorName: '', donorAddress: '80 Halls Hill Road, B Colchester, CT  6415', donation: '225'},
      {id: 70, studentName: 'Annika Wypyski', studentSection: 'Orange', studentGroup: 'E', donorOrg: '', donorName: 'Carly Piché', donorAddress: '1226 State Route 86 Saranac Lake, NY 12983', donation: '200'},
      {id: 71, studentName: 'Annika Wypyski', studentSection: 'Orange', studentGroup: 'E', donorOrg: 'OraLine', donorName: '', donorAddress: '135 Home Street Hosick Falls, NY 12090', donation: '225'},
      {id: 72, studentName: 'Emily Hardy', studentSection: 'Orange', studentGroup: 'E', donorOrg: '', donorName: '', donorAddress: '900 Wolcott Ave Beacon, NY 12508', donation: 'E Facilitator'},
      {id: 73, studentName: 'Emily Hardy', studentSection: 'Orange', studentGroup: 'E', donorOrg: 'Restwork LLC', donorName: '', donorAddress: '312 Second Ave Frankfort, NY 13340', donation: 'E Facilitator'},
      {id: 74, studentName: 'James DeLorenzo', studentSection: 'Orange', studentGroup: 'E', donorOrg: 'Town of Hoosick Lions Club', donorName: 'Sicilia Randazzo', donorAddress: '312 Second Ave Frankfort, NY 13340', donation: '200'},
      {id: 75, studentName: 'James DeLorenzo', studentSection: 'Orange', studentGroup: 'E', donorOrg: 'Beacon Elks Lodge 1493', donorName: 'Sicilia Randazzo', donorAddress: '241 Bishopville Loop The Villages, FL 32162', donation: '200'},
      {id: 76, studentName: 'Tahnia-Marie Rucker', studentSection: 'Orange', studentGroup: 'E', donorOrg: '', donorName: 'Linda Davis', donorAddress: 'PO Box 1023 Tupper Lake, NY 12986', donation: 'N J-Staff'},
      {id: 77, studentName: 'Tahnia-Marie Rucker', studentSection: 'Orange', studentGroup: 'E', donorOrg: '', donorName: '', donorAddress: '85 County Route 10 Germantown, NY 12526', donation: 'Speaker'},
      {id: 78, studentName: 'Zoe Boren', studentSection: 'Orange', studentGroup: 'E', donorOrg: '', donorName: 'Marrin Ludwig', donorAddress: '22 Corporate Woods Blvd, Suite 501 Albany, NY 12211', donation: '200'},
      {id: 79, studentName: 'Zoe Boren', studentSection: 'Orange', studentGroup: 'E', donorOrg: 'Kiwanis Club T L Service', donorName: 'Mara Afzail', donorAddress: 'PO Box 483 Chester, NY 10918', donation: '50'},
      {id: 80, studentName: 'Charonne Berthiaume', studentSection: 'Orange', studentGroup: 'F', donorOrg: '', donorName: '', donorAddress: '23 Ruby Lane Selkirk, NY 12158', donation: 'M J-Staff'},
      {id: 81, studentName: 'Charonne Berthiaume', studentSection: 'Orange', studentGroup: 'F', donorOrg: '', donorName: 'Kimberly Daoust', donorAddress: '135 Wilson Rd Sparrow Bush, NY 12780', donation: 'Ice Cream'},
      {id: 82, studentName: 'Cyane Ponce', studentSection: 'Orange', studentGroup: 'F', donorOrg: 'Kiwanis Club of Chester Inc', donorName: 'Ashley Emerson', donorAddress: '', donation: '225'},
      {id: 83, studentName: 'Cyane Ponce', studentSection: 'Orange', studentGroup: 'F', donorOrg: '', donorName: '', donorAddress: '23 Mariaville Rd Schenectady, NY 12306', donation: 'Speaker'},
      {id: 84, studentName: 'Ella Schoenborn', studentSection: 'Orange', studentGroup: 'F', donorOrg: '', donorName: '', donorAddress: '5 Computer Drive S Albany, NY 12205', donation: 'Speaker'},
      {id: 85, studentName: 'Ella Schoenborn', studentSection: 'Orange', studentGroup: 'F', donorOrg: 'Stewarts', donorName: 'Mark Eagan', donorAddress: '141 Washington Ave Albany, NY 12210', donation: 'H J-Staff'},
      {id: 86, studentName: 'Emma Summers', studentSection: 'Orange', studentGroup: 'F', donorOrg: 'Rotterdam Eagles', donorName: 'Deshanna Wiggins', donorAddress: '9 Falcon Crest Drive Johnstown, NY 12095', donation: '25'},
      {id: 87, studentName: 'Emma Summers', studentSection: 'Orange', studentGroup: 'F', donorOrg: '', donorName: 'Diya Patel', donorAddress: '2441 US Route 9W Ravena, NY 12143', donation: 'F Facilitator'},
      {id: 88, studentName: 'Emma Summers', studentSection: 'Orange', studentGroup: 'F', donorOrg: '', donorName: '', donorAddress: '209 Hy Vue Circle Newburgh, NY 12550', donation: '112.5'},
      {id: 89, studentName: 'Lily Stavanau', studentSection: 'Orange', studentGroup: 'F', donorOrg: '', donorName: 'Kyle Mast', donorAddress: 'PO Box 42 Selkirk, NY 12158', donation: 'Speaker'},
      {id: 90, studentName: 'Lily Stavanau', studentSection: 'Orange', studentGroup: 'F', donorOrg: 'Shear Creations Studio', donorName: 'Jackie Schrom', donorAddress: '141 Washington Ave Albany, NY 12210', donation: '200'},
      {id: 91, studentName: 'Lucien Niles', studentSection: 'Orange', studentGroup: 'F', donorOrg: '', donorName: 'Deshanna Wiggins', donorAddress: '3 Christine CT Latham, NY 12110', donation: '225'},
      {id: 92, studentName: 'Lucien Niles', studentSection: 'Orange', studentGroup: 'F', donorOrg: 'Bethlehem Grange No 137', donorName: '', donorAddress: '393 Old Loomis Rd Liberty, NY 12754', donation: '41.85'},
      {id: 93, studentName: 'Lucien Niles', studentSection: 'Orange', studentGroup: 'F', donorOrg: '', donorName: 'Carl Yaun', donorAddress: '', donation: 'Speaker'},
      {id: 94, studentName: 'Nithin Vinothkumar', studentSection: 'Orange', studentGroup: 'F', donorOrg: 'Kiwanis Club of Latham NY', donorName: '', donorAddress: '480 Broadway Saratoga Springs, NY 12866', donation: 'F Facilitator'},
      {id: 95, studentName: 'Nithin Vinothkumar', studentSection: 'Orange', studentGroup: 'F', donorOrg: '', donorName: 'Marcella Hammer', donorAddress: '209 Hy Vue Circle Newburgh, NY 12550', donation: '225'},
      {id: 96, studentName: 'Ronan Corr', studentSection: 'Orange', studentGroup: 'F', donorOrg: 'Benevity', donorName: 'Kyle Mast', donorAddress: '23 Mariaville Rd Schenectady, NY 12306', donation: '225'},
      {id: 97, studentName: 'Ronan Corr', studentSection: 'Orange', studentGroup: 'F', donorOrg: '', donorName: '', donorAddress: 'PO Box 331 Broadalbin, NY 12025', donation: '50'},
      {id: 98, studentName: 'Scottie-Lynn Dubuque', studentSection: 'Orange', studentGroup: 'F', donorOrg: '', donorName: '', donorAddress: '23 Ruby Lane Selkirk, NY 12158', donation: '100'},
      {id: 99, studentName: 'Scottie-Lynn Dubuque', studentSection: 'Orange', studentGroup: 'F', donorOrg: 'Rotterdam Eagles #3610', donorName: 'Kimberly Daoust', donorAddress: 'PO Box 363 Dover Plains, NY 12522', donation: 'Tolietries'},
      {id: 100, studentName: 'Dana Mosconi', studentSection: 'Yellow', studentGroup: 'G', donorOrg: 'Broadalbin Perth Lions Foundation', donorName: '', donorAddress: '', donation: 'Yellow Section Leader'},
      {id: 101, studentName: 'Dana Mosconi', studentSection: 'Yellow', studentGroup: 'G', donorOrg: '', donorName: '', donorAddress: '2000 F Street NW , Apt. #105 Washington, DC 20006', donation: '50'},
      {id: 102, studentName: 'Giana Kall', studentSection: 'Yellow', studentGroup: 'G', donorOrg: 'VFW Post 5444', donorName: 'Cody Ingraham', donorAddress: '144 Harrison Street Johnstown, NY 12095', donation: '250'},
      {id: 103, studentName: 'Giana Kall', studentSection: 'Yellow', studentGroup: 'G', donorOrg: 'OraLine', donorName: '', donorAddress: '280 Park Street Tupper Lake, NY 12986', donation: '50'},
      {id: 104, studentName: 'Juliette Wisniewski', studentSection: 'Yellow', studentGroup: 'G', donorOrg: '', donorName: 'Tawnya Bujold', donorAddress: '134 Cedar grove Rd Selkirk, NY 12158', donation: 'G Facilitator'},
      {id: 105, studentName: 'Juliette Wisniewski', studentSection: 'Yellow', studentGroup: 'G', donorOrg: 'Asante Sign Group', donorName: 'Patricia Grogan', donorAddress: '148 Monroe Ave. Brockport, NY 14420', donation: '100'},
      {id: 106, studentName: 'Laila Rabideau', studentSection: 'Yellow', studentGroup: 'G', donorOrg: 'Adirondack Regional Federal Credit Union', donorName: 'Seth Bailey', donorAddress: '41 W State St Johnstown, NY 12095', donation: 'G J-Staff'},
      {id: 107, studentName: 'Laila Rabideau', studentSection: 'Yellow', studentGroup: 'G', donorOrg: '', donorName: '', donorAddress: '87 N Chestnut St New Paltz, NY 12561', donation: '225'},
      {id: 108, studentName: 'Miles Frazier', studentSection: 'Yellow', studentGroup: 'G', donorOrg: '', donorName: 'Malana Douglas', donorAddress: '1226 State Route 86 Saranac Lake, NY 12983', donation: 'G Facilitator'},
      {id: 109, studentName: 'Miles Frazier', studentSection: 'Yellow', studentGroup: 'G', donorOrg: 'Mohan Stop and Shop', donorName: '', donorAddress: '148 Monroe Ave. Brockport, NY 14420', donation: 'back packs, floss, water bottles'},
      {id: 110, studentName: 'Rina Hernandez', studentSection: 'Yellow', studentGroup: 'G', donorOrg: '', donorName: 'Seth Bailey', donorAddress: '', donation: '225'},
      {id: 111, studentName: 'Rina Hernandez', studentSection: 'Yellow', studentGroup: 'G', donorOrg: 'Restwork LLC', donorName: '', donorAddress: '103 Montcalm St STE 1 Ticonderoga, NY 12883', donation: '225'},
      {id: 112, studentName: 'Tula Haley', studentSection: 'Yellow', studentGroup: 'G', donorOrg: '', donorName: '', donorAddress: 'PO Box 307 Chazy, NY 12921- 307', donation: 'Yellow Section Leader'},
      {id: 113, studentName: 'Tula Haley', studentSection: 'Yellow', studentGroup: 'G', donorOrg: 'Antham', donorName: '', donorAddress: '2000 F Street NW , Apt. #105 Washington, DC 20006', donation: '25'},
      {id: 114, studentName: 'Wynter Jarus', studentSection: 'Yellow', studentGroup: 'G', donorOrg: 'Knights of Columbus Ticonderoga Council 333', donorName: 'Cody Ingraham', donorAddress: '2441 US Route 9W Ravena, NY 12143', donation: 'H Facilitator'},
      {id: 115, studentName: 'Wynter Jarus', studentSection: 'Yellow', studentGroup: 'G', donorOrg: 'Chazy Lions Club', donorName: '', donorAddress: '59 Copperfield Dr Waterford, NY 12188', donation: '100'},
      {id: 116, studentName: 'Alina Arqam', studentSection: 'Yellow', studentGroup: 'H', donorOrg: '', donorName: 'Rhiannon Clauss', donorAddress: '41 W State St Johnstown, NY 12095', donation: '500'},
      {id: 117, studentName: 'Alina Arqam', studentSection: 'Yellow', studentGroup: 'H', donorOrg: 'Shear Creations Studio', donorName: '', donorAddress: '180 Schwenk Drive Kingston, NY 12401', donation: 'Speaker'},
      {id: 118, studentName: 'Angelina Riccio', studentSection: 'Yellow', studentGroup: 'H', donorOrg: '', donorName: 'Lynne White', donorAddress: '95-97 Ferry Street Troy, NY 12180', donation: 'C J-Staff'},
      {id: 119, studentName: 'Angelina Riccio', studentSection: 'Yellow', studentGroup: 'H', donorOrg: 'Mohan Stop and Shop', donorName: 'Jinah Ahn', donorAddress: '5 Maplewood Ter Goshen, NY 10924', donation: '50'},
      {id: 120, studentName: 'Brandin Wilson', studentSection: 'Yellow', studentGroup: 'H', donorOrg: 'Ulster Savings Bank', donorName: 'Henry Dong', donorAddress: '134 Cedar grove Rd Selkirk, NY 12158', donation: '225'},
      {id: 121, studentName: 'Brandin Wilson', studentSection: 'Yellow', studentGroup: 'H', donorOrg: '', donorName: 'Kevin Grogan', donorAddress: 'PO Box 331 Broadalbin, NY 12025', donation: '225'},
      {id: 122, studentName: 'Eva Parsons', studentSection: 'Yellow', studentGroup: 'H', donorOrg: '', donorName: '', donorAddress: 'PO Box 132 Greenville, NY 12083', donation: 'Speaker'},
      {id: 123, studentName: 'Eva Parsons', studentSection: 'Yellow', studentGroup: 'H', donorOrg: '', donorName: '', donorAddress: '32 Essex Street Albany, NY 12206', donation: 'H Facilitator'},
      {id: 124, studentName: 'Gisella Terralavoro', studentSection: 'Yellow', studentGroup: 'H', donorOrg: 'Broadalbin Perth Lions Foundation', donorName: 'Susan Lintner', donorAddress: '59 Copperfield Dr Waterford, NY 12188', donation: '225'},
      {id: 125, studentName: 'Gisella Terralavoro', studentSection: 'Yellow', studentGroup: 'H', donorOrg: 'Greenville American Legion', donorName: 'Rhiannon Clauss', donorAddress: '88 Main Street Ravena, NY 12143-1711', donation: 'Yellow Section Leader'},
      {id: 126, studentName: 'Gisella Terralavoro', studentSection: 'Yellow', studentGroup: 'H', donorOrg: '', donorName: '', donorAddress: '2000 F Street NW , Apt. #105 Washington, DC 20006', donation: '225'},
      {id: 127, studentName: 'Hope Williams', studentSection: 'Yellow', studentGroup: 'H', donorOrg: '', donorName: 'Cody Ingraham', donorAddress: '2880 Curry Rd Schenectady, NY 12303', donation: '500'},
      {id: 128, studentName: 'Hope Williams', studentSection: 'Yellow', studentGroup: 'H', donorOrg: 'Mueller\'s Automitive LLC', donorName: '', donorAddress: 'PO Box 42 Gallupville, NY 12073', donation: '225'},
      {id: 129, studentName: 'Kendall Boisvert', studentSection: 'Yellow', studentGroup: 'H', donorOrg: '', donorName: 'Ellen Snowdon', donorAddress: '88 Main Street Ravena, NY 12143-1711', donation: '500'},
      {id: 130, studentName: 'Kendall Boisvert', studentSection: 'Yellow', studentGroup: 'H', donorOrg: 'Long Energy', donorName: '', donorAddress: '3-7 Reed Street Coxsackie, NY 12051', donation: '225'},
      {id: 131, studentName: 'Nadeen Ahmed', studentSection: 'Yellow', studentGroup: 'H', donorOrg: 'Town of Wright/Schoharie Valley Lions Club', donorName: 'Nicole Bliess', donorAddress: '1 American Legion Rd Stillwater, NY 12170', donation: '1500'},
      {id: 132, studentName: 'Nadeen Ahmed', studentSection: 'Yellow', studentGroup: 'H', donorOrg: 'Mueller\'s Automitive LLC', donorName: '', donorAddress: '', donation: '26.02'},
      {id: 133, studentName: 'Sophia Patino', studentSection: 'Yellow', studentGroup: 'H', donorOrg: 'NB Coxsackie', donorName: '', donorAddress: '2402 Brandywine Parkway Guilderland, NY 20006', donation: 'Speaker'},
      {id: 134, studentName: 'Sophia Patino', studentSection: 'Yellow', studentGroup: 'H', donorOrg: 'American Legion Post 490', donorName: 'Courtland Ingraham', donorAddress: '32 Essex Street Albany, NY 12206', donation: 'I Facilitator'},
      {id: 135, studentName: 'Ava Pinto', studentSection: 'Yellow', studentGroup: 'I', donorOrg: 'Stewart\'s', donorName: 'Susan Lintner', donorAddress: '725 4th Ave, Apt JJ1 Brooklyn, NY 11232', donation: '25'},
      {id: 136, studentName: 'Ava Pinto', studentSection: 'Yellow', studentGroup: 'I', donorOrg: '', donorName: 'Elizabeth McGuoirk', donorAddress: '2441 US Route 9W Ravena, NY 12143', donation: '25'},
      {id: 137, studentName: 'Ava Pinto', studentSection: 'Yellow', studentGroup: 'I', donorOrg: '', donorName: '', donorAddress: '', donation: 'Speaker'},
      {id: 138, studentName: 'Charlotte Measeck', studentSection: 'Yellow', studentGroup: 'I', donorOrg: '', donorName: '', donorAddress: '1400 Washington Ave Albany, NY 12222', donation: '500'},
      {id: 139, studentName: 'Charlotte Measeck', studentSection: 'Yellow', studentGroup: 'I', donorOrg: 'Shear Creations Studio', donorName: 'Samuel Caldwell', donorAddress: 'PO Box 398 Jefferson, NY 12748', donation: 'Speaker'},
      {id: 140, studentName: 'Edward Lee', studentSection: 'Yellow', studentGroup: 'I', donorOrg: 'Thrivent', donorName: 'Jaclene Poley', donorAddress: '371 Whitehall Rd Albany, NY 12208', donation: '200'},
      {id: 141, studentName: 'Edward Lee', studentSection: 'Yellow', studentGroup: 'I', donorOrg: '', donorName: 'Brenda Baddam', donorAddress: '241 Bishopville Loop The Villages, FL 32162', donation: '51.74'},
      {id: 142, studentName: 'Hailey VanBramer', studentSection: 'Yellow', studentGroup: 'I', donorOrg: 'Jeff Bank', donorName: 'Gary Davis', donorAddress: '56 Meadow Rue Place Ballston Spa, NY 12020', donation: 'Speaker'},
      {id: 143, studentName: 'Hailey VanBramer', studentSection: 'Yellow', studentGroup: 'I', donorOrg: '', donorName: 'Dianne Schwarz', donorAddress: '1 Steuben Place Albany, NY 12207', donation: '250'},
      {id: 144, studentName: 'Mackenzi Marron', studentSection: 'Yellow', studentGroup: 'I', donorOrg: '', donorName: 'Angelique Powell', donorAddress: '280 Park Street Tupper Lake, NY 12986', donation: '100'},
      {id: 145, studentName: 'Mackenzi Marron', studentSection: 'Yellow', studentGroup: 'I', donorOrg: '', donorName: 'Tawnya Bujold', donorAddress: 'PO Box 194 Pawling, NY 12564', donation: 'Speaker'},
      {id: 146, studentName: 'Mackenzi Marron', studentSection: 'Yellow', studentGroup: 'I', donorOrg: '', donorName: '', donorAddress: '32 Essex Street Albany, NY 12206', donation: '25'},
      {id: 147, studentName: 'Marlie Lanzoni', studentSection: 'Yellow', studentGroup: 'I', donorOrg: 'Adirondack Regional Federal Credit Union', donorName: 'Susan Lintner', donorAddress: '', donation: 'Speaker'},
      {id: 148, studentName: 'Marlie Lanzoni', studentSection: 'Yellow', studentGroup: 'I', donorOrg: 'The Lions Club of Pawling', donorName: '', donorAddress: '81 Mohawk Street Rear Cohoes, NY 12047', donation: 'Speaker'},
      {id: 149, studentName: 'Marlie Lanzoni', studentSection: 'Yellow', studentGroup: 'I', donorOrg: '', donorName: 'Trent Griffin-Braaf', donorAddress: '141 Washington Ave Albany, NY 12210', donation: '225'},
      {id: 150, studentName: 'Norah Smerdon', studentSection: 'Yellow', studentGroup: 'I', donorOrg: 'Thrivent', donorName: 'Jahkeen Hoke', donorAddress: 'PO Box 2029 Scotia, NY 12302', donation: '103.19'},
      {id: 151, studentName: 'Norah Smerdon', studentSection: 'Yellow', studentGroup: 'I', donorOrg: '', donorName: '', donorAddress: '12 Whitman Ct Troy, NY 12180', donation: 'Speaker'},
      {id: 152, studentName: 'Norah Smerdon', studentSection: 'Yellow', studentGroup: 'I', donorOrg: '', donorName: 'Cara Sherwood', donorAddress: '', donation: 'T J-Staff'},
      {id: 153, studentName: 'Payton Sutryk', studentSection: 'Yellow', studentGroup: 'I', donorOrg: 'Scotia Rotary Club', donorName: 'Walter Thorne', donorAddress: '10 Birchwood Drive New Windsor, NY 12553', donation: 'Speaker'},
      {id: 154, studentName: 'Payton Sutryk', studentSection: 'Yellow', studentGroup: 'I', donorOrg: '', donorName: 'Grace Musante', donorAddress: '200 Green Street Albany, NY 12202', donation: 'I Facilitator'},
      {id: 155, studentName: 'Payton Sutryk', studentSection: 'Yellow', studentGroup: 'I', donorOrg: '', donorName: 'Paul "Batman" Collins-Hackett', donorAddress: '725 4th Ave, Apt JJ1 Brooklyn, NY 11232', donation: '100'},
      {id: 156, studentName: 'Sophie Cottrell', studentSection: 'Yellow', studentGroup: 'I', donorOrg: '', donorName: 'Elizabeth McGuoirk', donorAddress: '41 W State St Johnstown, NY 12095', donation: 'Green Section Leader'},
      {id: 157, studentName: 'Sophie Cottrell', studentSection: 'Yellow', studentGroup: 'I', donorOrg: '', donorName: '', donorAddress: '20 Caraway Ln Spencerport, NY 14559', donation: '50'},
      {id: 158, studentName: 'Violette Wallace', studentSection: 'Yellow', studentGroup: 'I', donorOrg: '', donorName: 'Meghan Myers', donorAddress: '134 Cedar grove Rd Selkirk, NY 12158', donation: '225'},
      {id: 159, studentName: 'Violette Wallace', studentSection: 'Yellow', studentGroup: 'I', donorOrg: 'Mohan Stop and Shop', donorName: 'Kevin Grogan', donorAddress: '84 Chestnut Street Oneonta, NY 13820', donation: 'Speaker'},
      {id: 160, studentName: 'Aubrie Werne', studentSection: 'Green', studentGroup: 'J', donorOrg: '', donorName: '', donorAddress: '2 Marconi Drive Latham, NY 12110', donation: 'Speaker'},
      {id: 161, studentName: 'Aubrie Werne', studentSection: 'Green', studentGroup: 'J', donorOrg: '', donorName: 'Nicholas Francella', donorAddress: '141 Washington Ave Albany, NY 12210', donation: 'Green Section Leader'},
      {id: 162, studentName: 'Ayla Naselli', studentSection: 'Green', studentGroup: 'J', donorOrg: 'Oneonta Elks Lodge', donorName: 'Deshanna Wiggins', donorAddress: '20 Caraway Ln Spencerport, NY 14559', donation: '25'},
      {id: 163, studentName: 'Ayla Naselli', studentSection: 'Green', studentGroup: 'J', donorOrg: '', donorName: 'Meghan Myers', donorAddress: '99 Main St Ravena, NY 12143', donation: 'F J-Staff'},
      {id: 164, studentName: 'Ayla Naselli', studentSection: 'Green', studentGroup: 'J', donorOrg: '', donorName: '', donorAddress: '4 Bouchard Dr Peru, NY 12972', donation: '225'},
      {id: 165, studentName: 'Carley Vanzetta', studentSection: 'Green', studentGroup: 'J', donorOrg: '', donorName: 'Z Young', donorAddress: '14 Upper Hillman Rd Warwick, NY 10990-2636', donation: 'J Facilitator'},
      {id: 166, studentName: 'Carley Vanzetta', studentSection: 'Green', studentGroup: 'J', donorOrg: 'Persico True Value', donorName: 'Tyler Carey', donorAddress: '93 Keith Drive Poughkeepsie, NY 12603', donation: '225'},
      {id: 167, studentName: 'Connor Gierloff', studentSection: 'Green', studentGroup: 'J', donorOrg: '', donorName: 'Zeyad Zoha', donorAddress: '142 Main Street Goshen, NY 10924', donation: 'J Facilitator'},
      {id: 168, studentName: 'Connor Gierloff', studentSection: 'Green', studentGroup: 'J', donorOrg: '', donorName: 'Gao Shen', donorAddress: '93 Keith Drive Poughkeepsie, NY 12603', donation: '225'},
      {id: 169, studentName: 'Jillian Decker', studentSection: 'Green', studentGroup: 'J', donorOrg: '', donorName: 'Zeyad Zoha', donorAddress: '2880 Curry Rd Schenectady, NY 12303', donation: '225'},
      {id: 170, studentName: 'Jillian Decker', studentSection: 'Green', studentGroup: 'J', donorOrg: '', donorName: '', donorAddress: 'PO Box 2064 Plattsburgh, NY 12901', donation: 'Speaker'},
      {id: 171, studentName: 'Lydia Nebesnik', studentSection: 'Green', studentGroup: 'J', donorOrg: '', donorName: 'Nancy Church', donorAddress: '200 Green Street Albany, NY 12202', donation: '200'},
      {id: 172, studentName: 'Lydia Nebesnik', studentSection: 'Green', studentGroup: 'J', donorOrg: 'Long Energy', donorName: 'Paul "Batman" Collins-Hackett', donorAddress: '241 Bishopville Loop The Villages, FL 32162', donation: '51.74'},
      {id: 173, studentName: 'Nathan D\'Ordine', studentSection: 'Green', studentGroup: 'J', donorOrg: 'Kiwanis Club of Plattsburgh (Noon Club)', donorName: 'Gary Davis', donorAddress: '56 Meadow Rue Place Ballston Spa, NY 12020', donation: 'Speaker'},
      {id: 174, studentName: 'Nathan D\'Ordine', studentSection: 'Green', studentGroup: 'J', donorOrg: '', donorName: 'Dianne Schwarz', donorAddress: '1 Steuben Place Albany, NY 12207', donation: 'U J-Staff'},
      {id: 175, studentName: 'Payton Bashaw', studentSection: 'Green', studentGroup: 'J', donorOrg: '', donorName: 'Angelique Powell', donorAddress: '529 Laurel rd  Ridgwood, NJ  7450', donation: 'Speaker'},
      {id: 176, studentName: 'Payton Bashaw', studentSection: 'Green', studentGroup: 'J', donorOrg: '', donorName: 'Audrey Hall', donorAddress: '22 Corporate Woods Blvd, Suite 501 Albany, NY 12211', donation: 'K Facilitator'},
      {id: 177, studentName: 'Payton Bashaw', studentSection: 'Green', studentGroup: 'J', donorOrg: '', donorName: 'Mara Afzail', donorAddress: '312 Second Ave Frankfort, NY 13340', donation: '225'},
      {id: 178, studentName: 'Saoirse Trazino', studentSection: 'Green', studentGroup: 'J', donorOrg: '', donorName: 'Sofia Randazzo', donorAddress: '142 Main Street Goshen, NY 10924', donation: 'Speaker'},
      {id: 179, studentName: 'Saoirse Trazino', studentSection: 'Green', studentGroup: 'J', donorOrg: '', donorName: 'Gao Shen', donorAddress: '141 Washington Ave Albany, NY 12210', donation: '100'},
      {id: 180, studentName: 'Aveline Hellings', studentSection: 'Green', studentGroup: 'K', donorOrg: '', donorName: 'Deshanna Wiggins', donorAddress: 'PO Box 363 Dover Plains, NY 12522', donation: '225'},
      {id: 181, studentName: 'Aveline Hellings', studentSection: 'Green', studentGroup: 'K', donorOrg: '', donorName: '', donorAddress: '393 Old Loomis Rd Liberty, NY 12754', donation: 'Green Section Leader'},
      {id: 182, studentName: 'Aveline Hellings', studentSection: 'Green', studentGroup: 'K', donorOrg: '', donorName: 'Carl Yaun', donorAddress: '20 Caraway Ln Spencerport, NY 14559', donation: '50'},
      {id: 183, studentName: 'Carissa Loffredo', studentSection: 'Green', studentGroup: 'K', donorOrg: 'VFW Post 5444', donorName: 'Meghan Myers', donorAddress: '134 Cedar grove Rd Selkirk, NY 12158', donation: 'K Facilitator'},
      {id: 184, studentName: 'Carissa Loffredo', studentSection: 'Green', studentGroup: 'K', donorOrg: '', donorName: 'Patricia Grogan', donorAddress: '312 Second Ave Frankfort, NY 13340', donation: '225'},
      {id: 185, studentName: 'Dylan Foss', studentSection: 'Green', studentGroup: 'K', donorOrg: '', donorName: 'Sofia Randazzo', donorAddress: '14 Upper Hillman Rd Warwick, NY 10990-2636', donation: '200'},
      {id: 186, studentName: 'Dylan Foss', studentSection: 'Green', studentGroup: 'K', donorOrg: '', donorName: 'Tyler Carey', donorAddress: '241 Bishopville Loop The Villages, FL 32162', donation: '50'},
      {id: 187, studentName: 'Isabella Barrett', studentSection: 'Green', studentGroup: 'K', donorOrg: '', donorName: 'Linda Davis', donorAddress: '90 Green Street Hudson, NY 12534', donation: '225'},
      {id: 188, studentName: 'Isabella Barrett', studentSection: 'Green', studentGroup: 'K', donorOrg: '', donorName: '', donorAddress: 'PO Box 642 Malone, NY 12953', donation: 'Ice Cream'},
      {id: 189, studentName: 'Lindsey Shanley', studentSection: 'Green', studentGroup: 'K', donorOrg: '', donorName: '', donorAddress: '', donation: 'D J-Staff'},
      {id: 190, studentName: 'Lindsey Shanley', studentSection: 'Green', studentGroup: 'K', donorOrg: 'Since 1914 LLC', donorName: '', donorAddress: '85 Macey Lane Plattsburgh, NY 12901', donation: '225'},
      {id: 191, studentName: 'Lucas Walsh', studentSection: 'Green', studentGroup: 'K', donorOrg: 'Kiwanis Club of Malone NY', donorName: 'Nathaniel De Boos', donorAddress: '1226 State Route 86 Saranac Lake, NY 12983', donation: 'L Facilitator'},
      {id: 192, studentName: 'Lucas Walsh', studentSection: 'Green', studentGroup: 'K', donorOrg: 'Stewarts', donorName: '', donorAddress: '6135 State Highway 7, Apartment 1 Oneonta, NY 13820', donation: '50'},
      {id: 193, studentName: 'Anna Grace Macica', studentSection: 'Green', studentGroup: 'L', donorOrg: '', donorName: 'Autumn Welsh-Travis', donorAddress: '90 Green Street Hudson, NY 12534', donation: '225'},
      {id: 194, studentName: 'Anna Grace Macica', studentSection: 'Green', studentGroup: 'L', donorOrg: 'Restwork LLC', donorName: '', donorAddress: 'PO BOx 701 Nassau, NY 12123', donation: '50'},
      {id: 195, studentName: 'Ava Carroll', studentSection: 'Green', studentGroup: 'L', donorOrg: '', donorName: '', donorAddress: '23 Ruby Lane Selkirk, NY 12158', donation: '225'},
      {id: 196, studentName: 'Ava Carroll', studentSection: 'Green', studentGroup: 'L', donorOrg: 'Since 1914 LLC', donorName: 'Kimberly Daoust', donorAddress: 'PO Box 255 Roscoe, NY 12776', donation: '225'},
      {id: 197, studentName: 'Brooke Battiato', studentSection: 'Green', studentGroup: 'L', donorOrg: 'Chandler Young VFW Post 8162', donorName: '', donorAddress: 'PO Box 1193 Cooperstown, NY 13326', donation: 'Speaker'},
      {id: 198, studentName: 'Brooke Battiato', studentSection: 'Green', studentGroup: 'L', donorOrg: '', donorName: '', donorAddress: '32 Essex Street Albany, NY 12206', donation: 'L Facilitator'},
      {id: 199, studentName: 'Elijah Lee', studentSection: 'Green', studentGroup: 'L', donorOrg: 'Kiwanis Club of Roscoe', donorName: 'Susan Lintner', donorAddress: '6135 State Highway 7, Apartment 1 Oneonta, NY 13820', donation: 'back packs, floss, water bottles'},
      {id: 200, studentName: 'Elijah Lee', studentSection: 'Green', studentGroup: 'L', donorOrg: 'American Legion', donorName: 'Autumn Welsh-Travis', donorAddress: '', donation: 'A J-Staff'},
      {id: 201, studentName: 'Elijah Lee', studentSection: 'Green', studentGroup: 'L', donorOrg: '', donorName: '', donorAddress: '47 Birch Ln Holmes, NY 12531', donation: '25'},
      {id: 202, studentName: 'Greyson Ludwig', studentSection: 'Green', studentGroup: 'L', donorOrg: '', donorName: 'Madelyn Clark', donorAddress: '99 Main St Ravena, NY 12143', donation: '500'},
      {id: 203, studentName: 'Greyson Ludwig', studentSection: 'Green', studentGroup: 'L', donorOrg: 'Antham', donorName: '', donorAddress: '180 Schwenk Drive Kingston, NY 12401', donation: '50'},
      {id: 204, studentName: 'Halley LaBrecque', studentSection: 'Green', studentGroup: 'L', donorOrg: '', donorName: 'Lynne White', donorAddress: '134 Cedar grove Rd Selkirk, NY 12158', donation: 'Speaker'},
      {id: 205, studentName: 'Halley LaBrecque', studentSection: 'Green', studentGroup: 'L', donorOrg: 'Persico True Value', donorName: 'Kevin Grogan', donorAddress: '141 Washington Ave Albany, NY 12210', donation: '225'},
      {id: 206, studentName: 'Nessa Wendell', studentSection: 'Green', studentGroup: 'L', donorOrg: 'Ulster Savings Bank', donorName: 'Deshanna Wiggins', donorAddress: 'PO Box 1118 Pine Bush, NY 12566', donation: 'Speaker'},
      {id: 207, studentName: 'Nessa Wendell', studentSection: 'Green', studentGroup: 'L', donorOrg: '', donorName: '', donorAddress: '480 Broadway Saratoga Springs, NY 12866', donation: 'Speaker'},
      {id: 208, studentName: 'Nessa Wendell', studentSection: 'Green', studentGroup: 'L', donorOrg: '', donorName: 'Marcella Hammer', donorAddress: '', donation: '500'},
      {id: 209, studentName: 'Rihanna Scott', studentSection: 'Green', studentGroup: 'L', donorOrg: 'Pine Bush Lions Club', donorName: 'Walter Thorne', donorAddress: '180 Schwenk Drive Kingston, NY 12401', donation: '20'},
      {id: 210, studentName: 'Rihanna Scott', studentSection: 'Green', studentGroup: 'L', donorOrg: '', donorName: 'Lynne White', donorAddress: '', donation: 'Speaker'},
      {id: 211, studentName: 'Rihanna Scott', studentSection: 'Green', studentGroup: 'L', donorOrg: '', donorName: 'John Swartwout', donorAddress: '', donation: '25'},
      {id: 212, studentName: 'Victoria Forte', studentSection: 'Green', studentGroup: 'L', donorOrg: 'Ulster Savings Bank', donorName: 'Ben Williams', donorAddress: '', donation: 'Speaker'},
      {id: 213, studentName: 'Victoria Forte', studentSection: 'Green', studentGroup: 'L', donorOrg: '', donorName: '', donorAddress: '4 Century Hill Drive Latham, NY 12110', donation: 'Speaker'},
      {id: 214, studentName: 'Victoria Forte', studentSection: 'Green', studentGroup: 'L', donorOrg: '', donorName: 'LB Hannahs', donorAddress: '', donation: 'Blue Section Leader'},
      {id: 215, studentName: 'Anthony Villavicencio', studentSection: 'Blue', studentGroup: 'M', donorOrg: 'Thrivent', donorName: 'Walter Thorne', donorAddress: '222 Snook Rd Fishkill, NY 12524', donation: '50'},
      {id: 216, studentName: 'Anthony Villavicencio', studentSection: 'Blue', studentGroup: 'M', donorOrg: '', donorName: 'Amanda Walshjamin', donorAddress: '90 Green Street Hudson, NY 12534', donation: '200'},
      {id: 217, studentName: 'Anthony Villavicencio', studentSection: 'Blue', studentGroup: 'M', donorOrg: '', donorName: '', donorAddress: '241 Bishopville Loop The Villages, FL 32162', donation: '26.02'},
      {id: 218, studentName: 'Braden Pisani', studentSection: 'Blue', studentGroup: 'M', donorOrg: '', donorName: 'Gary Davis', donorAddress: '2402 Brandywine Parkway Guilderland, NY 20006', donation: 'Speaker'},
      {id: 219, studentName: 'Braden Pisani', studentSection: 'Blue', studentGroup: 'M', donorOrg: 'Since 1914 LLC', donorName: 'Courtland Ingraham', donorAddress: '141 Washington Ave Albany, NY 12210', donation: '250'},
      {id: 220, studentName: 'Jason Yao', studentSection: 'Blue', studentGroup: 'M', donorOrg: '', donorName: 'Jahkeen Hoke', donorAddress: '', donation: 'Speaker'},
      {id: 221, studentName: 'Jason Yao', studentSection: 'Blue', studentGroup: 'M', donorOrg: '', donorName: '', donorAddress: '81 Mohawk Street Rear Cohoes, NY 12047', donation: '1500'},
      {id: 222, studentName: 'Jason Yao', studentSection: 'Blue', studentGroup: 'M', donorOrg: '', donorName: 'Trent Griffin-Braaf', donorAddress: '', donation: '103.19'},
      {id: 223, studentName: 'Jessica Morris', studentSection: 'Blue', studentGroup: 'M', donorOrg: 'Thrivent', donorName: '', donorAddress: '12 Whitman Ct Troy, NY 12180', donation: 'Speaker'},
      {id: 224, studentName: 'Jessica Morris', studentSection: 'Blue', studentGroup: 'M', donorOrg: '', donorName: 'Cara Sherwood', donorAddress: '1 Steuben Place Albany, NY 12207', donation: '225'},
      {id: 225, studentName: 'Julia Skidmore', studentSection: 'Blue', studentGroup: 'M', donorOrg: 'Stewart\'s', donorName: 'Angelique Powell', donorAddress: 'PO Box 274 Cornwall, NY 12518', donation: 'Speaker'},
      {id: 226, studentName: 'Julia Skidmore', studentSection: 'Blue', studentGroup: 'M', donorOrg: '', donorName: '', donorAddress: '81 Mohawk Street Rear Cohoes, NY 12047', donation: '500'},
      {id: 227, studentName: 'Julia Skidmore', studentSection: 'Blue', studentGroup: 'M', donorOrg: '', donorName: 'Trent Griffin-Braaf', donorAddress: '2 Jefferson Plaza Poughkeepsie, NY 12601', donation: '20'},
      {id: 228, studentName: 'Kathleen OConnor', studentSection: 'Blue', studentGroup: 'M', donorOrg: 'The Cornwall Lions Club Inc', donorName: 'Michael Quinn', donorAddress: '4901 South Catherine Str Plattsburgh, NY 12901', donation: 'Speaker'},
      {id: 229, studentName: 'Kathleen OConnor', studentSection: 'Blue', studentGroup: 'M', donorOrg: '', donorName: 'Debby Cech', donorAddress: '', donation: '250'},
      {id: 230, studentName: 'Paige Kropp', studentSection: 'Blue', studentGroup: 'M', donorOrg: 'Rhinebeck Bank', donorName: 'Ben Williams', donorAddress: '', donation: 'Speaker'},
      {id: 231, studentName: 'Paige Kropp', studentSection: 'Blue', studentGroup: 'M', donorOrg: '', donorName: '', donorAddress: '4 Century Hill Drive Latham, NY 12110', donation: '25'},
      {id: 232, studentName: 'Paige Kropp', studentSection: 'Blue', studentGroup: 'M', donorOrg: '', donorName: 'LB Hannahs', donorAddress: '', donation: 'Speaker'},
      {id: 233, studentName: 'Reagan Whitney', studentSection: 'Blue', studentGroup: 'M', donorOrg: 'Thrivent', donorName: '', donorAddress: '5 Computer Drive S Albany, NY 12205', donation: '250'},
      {id: 234, studentName: 'Reagan Whitney', studentSection: 'Blue', studentGroup: 'M', donorOrg: '', donorName: 'Mark Eagan', donorAddress: '', donation: '20'},
      {id: 235, studentName: 'Violet Aufdenberg', studentSection: 'Blue', studentGroup: 'M', donorOrg: 'Thrivent', donorName: '', donorAddress: '', donation: '225'},
      {id: 236, studentName: 'Violet Aufdenberg', studentSection: 'Blue', studentGroup: 'M', donorOrg: '', donorName: 'John Swartwout', donorAddress: '710 Pleasant Street Peru, NY 12972', donation: 'Speaker'},
      {id: 237, studentName: 'Zoee Corrigan', studentSection: 'Blue', studentGroup: 'M', donorOrg: 'Thrivent', donorName: '', donorAddress: '480 Broadway Saratoga Springs, NY 12866', donation: 'Speaker'},
      {id: 238, studentName: 'Zoee Corrigan', studentSection: 'Blue', studentGroup: 'M', donorOrg: '', donorName: 'Marcella Hammer', donorAddress: '', donation: '2000'},
      {id: 239, studentName: 'Abdeen Zaggout', studentSection: 'Blue', studentGroup: 'N', donorOrg: 'Peru Memorial VFW Post #309', donorName: 'Walter Thorne', donorAddress: '384 North Grand Street Cobleskill, NY 12043', donation: 'Speaker'},
      {id: 240, studentName: 'Abdeen Zaggout', studentSection: 'Blue', studentGroup: 'N', donorOrg: '', donorName: '', donorAddress: '480 Broadway Saratoga Springs, NY 12866', donation: '200'},
      {id: 241, studentName: 'Abdeen Zaggout', studentSection: 'Blue', studentGroup: 'N', donorOrg: '', donorName: 'Marcella Hammer', donorAddress: 'PO Box 165 Peru, NY 12972', donation: '50'},
      {id: 242, studentName: 'Andre Shaw', studentSection: 'Blue', studentGroup: 'N', donorOrg: 'Fenimore Assett Management', donorName: '', donorAddress: '144 Harrison Street Johnstown, NY 12095', donation: '225'},
      {id: 243, studentName: 'Andre Shaw', studentSection: 'Blue', studentGroup: 'N', donorOrg: '', donorName: '', donorAddress: '11 Linden Park Drive Halfmoon, NY 12065', donation: '225'},
      {id: 244, studentName: 'Ashton Metz', studentSection: 'Blue', studentGroup: 'N', donorOrg: 'Peru Lions Club', donorName: '', donorAddress: '2880 Curry Rd Schenectady, NY 12303', donation: 'N Facilitator'},
      {id: 245, studentName: 'Ashton Metz', studentSection: 'Blue', studentGroup: 'N', donorOrg: 'Asante Sign Group', donorName: '', donorAddress: '140 Jefferson St, APT 2 Albany, NY 12210', donation: 'Tolietries'},
      {id: 246, studentName: 'Chloe Wright', studentSection: 'Blue', studentGroup: 'N', donorOrg: 'GFWC-NY Southern Saratoga Women\'s Club', donorName: 'Hannah Pell', donorAddress: '', donation: '225'},
      {id: 247, studentName: 'Chloe Wright', studentSection: 'Blue', studentGroup: 'N', donorOrg: 'Long Energy', donorName: '', donorAddress: 'PO Box 546 Ballston Spa, NY 12020', donation: '225'},
      {id: 248, studentName: 'Eleanor Firestone', studentSection: 'Blue', studentGroup: 'N', donorOrg: '', donorName: '', donorAddress: '315 Maryann Way Northvale, NJ  7647', donation: '225'},
      {id: 249, studentName: 'Eleanor Firestone', studentSection: 'Blue', studentGroup: 'N', donorOrg: 'OraLine', donorName: 'Bernadette Daurio', donorAddress: '68 East North Street Ballston Spa, NY 12020-1223', donation: '20'},
      {id: 250, studentName: 'Elexis Martin', studentSection: 'Blue', studentGroup: 'N', donorOrg: 'Ballston Spa Rotary Club', donorName: '', donorAddress: '', donation: 'N Facilitator'},
      {id: 251, studentName: 'Elexis Martin', studentSection: 'Blue', studentGroup: 'N', donorOrg: '', donorName: 'John Swartwout', donorAddress: '140 Jefferson St, APT 2 Albany, NY 12210', donation: 'Speaker'},
      {id: 252, studentName: 'Ella Olsen', studentSection: 'Blue', studentGroup: 'N', donorOrg: 'Veterans of Foreign Wars Ballston Spa Post 358', donorName: 'Hannah Pell', donorAddress: '200 Green Street Albany, NY 12202', donation: 'Blue Section Leader'},
      {id: 253, studentName: 'Ella Olsen', studentSection: 'Blue', studentGroup: 'N', donorOrg: '', donorName: 'Paul "Batman" Collins-Hackett', donorAddress: '222 Snook Rd Fishkill, NY 12524', donation: '50'},
      {id: 254, studentName: 'Madelynn Baxter', studentSection: 'Blue', studentGroup: 'N', donorOrg: '', donorName: 'Amanda Walshjamin', donorAddress: '144 Harrison Street Johnstown, NY 12095', donation: 'O Facilitator'},
      {id: 255, studentName: 'Madelynn Baxter', studentSection: 'Blue', studentGroup: 'N', donorOrg: '', donorName: '', donorAddress: '2402 Brandywine Parkway Guilderland, NY 12084', donation: 'Ice Cream'},
      {id: 256, studentName: 'Autumn Montanez', studentSection: 'Blue', studentGroup: 'O', donorOrg: '', donorName: 'Colin Ingraham', donorAddress: '', donation: '200'},
      {id: 257, studentName: 'Autumn Montanez', studentSection: 'Blue', studentGroup: 'O', donorOrg: 'Asante Sign Group', donorName: '', donorAddress: 'PO Box 113 East Greenbush, NY 12061', donation: '225'},
      {id: 258, studentName: 'Hailey Richards', studentSection: 'Blue', studentGroup: 'O', donorOrg: '', donorName: '', donorAddress: '315 Maryann Way Northvale, NJ  7647', donation: 'O Facilitator'},
      {id: 259, studentName: 'Hailey Richards', studentSection: 'Blue', studentGroup: 'O', donorOrg: 'Stewarts', donorName: 'Bernadette Daurio', donorAddress: '2402 Brandywine Parkway Guilderland, NY 12084', donation: 'Speaker'},
      {id: 260, studentName: 'Isabella Forsey', studentSection: 'Blue', studentGroup: 'O', donorOrg: 'Kiwanis Club of East Greenbush', donorName: 'Colin Ingraham', donorAddress: '22 Corporate Woods Blvd, Suite 501 Albany, NY 12211', donation: 'Blue Section Leader'},
      {id: 261, studentName: 'Isabella Forsey', studentSection: 'Blue', studentGroup: 'O', donorOrg: '', donorName: 'Mara Afzail', donorAddress: '222 Snook Rd Fishkill, NY 12524', donation: 'back packs, floss, water bottles'},
      {id: 262, studentName: 'Rachael Gerber', studentSection: 'Blue', studentGroup: 'O', donorOrg: '', donorName: 'Amanda Walshjamin', donorAddress: '', donation: '500'},
      {id: 263, studentName: 'Rachael Gerber', studentSection: 'Blue', studentGroup: 'O', donorOrg: '', donorName: '', donorAddress: '3-7 Reed Street Coxsackie, NY 12051', donation: '225'},
      {id: 264, studentName: 'Ruoxi Zhan', studentSection: 'Blue', studentGroup: 'O', donorOrg: '', donorName: 'Nicole Bliess', donorAddress: '315 Maryann Way Northvale, NJ  7647', donation: 'O J-Staff'},
      {id: 265, studentName: 'Ruoxi Zhan', studentSection: 'Blue', studentGroup: 'O', donorOrg: 'Antham', donorName: 'Bernadette Daurio', donorAddress: '80 Stony Brook Drive  Selkirk, NY 12158', donation: '250'},
      {id: 266, studentName: 'Sophia Blauberg', studentSection: 'Blue', studentGroup: 'O', donorOrg: 'NB Coxsackie', donorName: 'ana ball', donorAddress: '', donation: '2000'},
      {id: 267, studentName: 'Sophia Blauberg', studentSection: 'Blue', studentGroup: 'O', donorOrg: '', donorName: '', donorAddress: '384 North Grand Street Cobleskill, NY 12043', donation: 'Speaker'},
      {id: 268, studentName: 'Sophia LaBarge', studentSection: 'Blue', studentGroup: 'O', donorOrg: '', donorName: '', donorAddress: '2 Marconi Drive Latham, NY 12110', donation: '250'},
      {id: 269, studentName: 'Sophia LaBarge', studentSection: 'Blue', studentGroup: 'O', donorOrg: 'Price Chopper', donorName: 'Nicholas Francella', donorAddress: '', donation: 'Speaker'},
      {id: 270, studentName: 'Andrea Favinger', studentSection: 'Purple', studentGroup: 'P', donorOrg: 'Fenimore Assett Management', donorName: '', donorAddress: '81 Mohawk Street Rear Cohoes, NY 12047', donation: 'P Facilitator'},
      {id: 271, studentName: 'Andrea Favinger', studentSection: 'Purple', studentGroup: 'P', donorOrg: '', donorName: 'Trent Griffin-Braaf', donorAddress: '275 River St Troy, NY 12180', donation: 'Speaker'},
      {id: 272, studentName: 'Bella Togias', studentSection: 'Purple', studentGroup: 'P', donorOrg: 'Thrivent', donorName: 'Isabella Marchese', donorAddress: '95-97 Ferry Street Troy, NY 12180', donation: 'P Facilitator'},
      {id: 273, studentName: 'Bella Togias', studentSection: 'Purple', studentGroup: 'P', donorOrg: '', donorName: 'Jinah Ahn', donorAddress: '275 River St Troy, NY 12180', donation: 'Ice Cream'},
      {id: 274, studentName: 'Davonna Shaw', studentSection: 'Purple', studentGroup: 'P', donorOrg: '', donorName: 'Isabella Marchese', donorAddress: '', donation: '225'},
      {id: 275, studentName: 'Davonna Shaw', studentSection: 'Purple', studentGroup: 'P', donorOrg: '', donorName: '', donorAddress: '4 Ridge Ave Port Jervis, NY 12771', donation: '50'},
      {id: 276, studentName: 'Dev Bhatia', studentSection: 'Purple', studentGroup: 'P', donorOrg: '', donorName: '', donorAddress: '90 Green Street Hudson, NY 12534', donation: 'Purple Section Leader'},
      {id: 277, studentName: 'Dev Bhatia', studentSection: 'Purple', studentGroup: 'P', donorOrg: 'Stewarts', donorName: '', donorAddress: '76 North Pearl St, Apt 407 Albany, NY 12207', donation: 'Speaker'},
      {id: 278, studentName: 'Julia Williams', studentSection: 'Purple', studentGroup: 'P', donorOrg: 'Town of Deerpark Lions Club', donorName: 'Macy Hayes', donorAddress: '95-97 Ferry Street Troy, NY 12180', donation: '500'},
      {id: 279, studentName: 'Julia Williams', studentSection: 'Purple', studentGroup: 'P', donorOrg: 'Since 1914 LLC', donorName: 'Jinah Ahn', donorAddress: '3-7 Reed Street Coxsackie, NY 12051', donation: '20'},
      {id: 280, studentName: 'Landon Ploss', studentSection: 'Purple', studentGroup: 'P', donorOrg: '', donorName: 'Nicole Bliess', donorAddress: '4901 South Catherine Str Plattsburgh, NY 12901', donation: 'Speaker'},
      {id: 281, studentName: 'Landon Ploss', studentSection: 'Purple', studentGroup: 'P', donorOrg: '', donorName: 'Debby Cech', donorAddress: '', donation: '25'},
      {id: 282, studentName: 'Anne Lendrum', studentSection: 'Purple', studentGroup: 'Q', donorOrg: 'NB Coxsackie', donorName: 'Ben Williams', donorAddress: '', donation: 'Speaker'},
      {id: 283, studentName: 'Anne Lendrum', studentSection: 'Purple', studentGroup: 'Q', donorOrg: '', donorName: '', donorAddress: '5 Computer Drive S Albany, NY 12205', donation: 'Speaker'},
      {id: 284, studentName: 'Anne Lendrum', studentSection: 'Purple', studentGroup: 'Q', donorOrg: '', donorName: 'Mark Eagan', donorAddress: '4 Century Hill Drive Latham, NY 12110', donation: '200'},
      {id: 285, studentName: 'Caroline Sottile', studentSection: 'Purple', studentGroup: 'Q', donorOrg: 'Thrivent', donorName: 'LB Hannahs', donorAddress: '3 Christine CT Latham, NY 12110', donation: '225'},
      {id: 286, studentName: 'Caroline Sottile', studentSection: 'Purple', studentGroup: 'Q', donorOrg: '', donorName: '', donorAddress: 'PO Box 1193 Cooperstown, NY 13326', donation: '500'},
      {id: 287, studentName: 'Caroline Sottile', studentSection: 'Purple', studentGroup: 'Q', donorOrg: '', donorName: '', donorAddress: '643 Rt 211 East Suite 1 Middletown, NY 10941', donation: '20'},
      {id: 288, studentName: 'Dahlia Levinson', studentSection: 'Purple', studentGroup: 'Q', donorOrg: 'Kiwanis Club of Latham NY', donorName: 'Dawn Martinez', donorAddress: '4901 South Catherine Str Plattsburgh, NY 12901', donation: 'Speaker'},
      {id: 289, studentName: 'Dahlia Levinson', studentSection: 'Purple', studentGroup: 'Q', donorOrg: 'American Legion', donorName: 'Debby Cech', donorAddress: '', donation: '200'},
      {id: 290, studentName: 'Emily Fanniff', studentSection: 'Purple', studentGroup: 'Q', donorOrg: 'Catskill Hudson Bank', donorName: 'Ben Williams', donorAddress: 'PO Box 62 Napanoch, NY 12458', donation: 'Speaker'},
      {id: 291, studentName: 'Emily Fanniff', studentSection: 'Purple', studentGroup: 'Q', donorOrg: '', donorName: '', donorAddress: '1400 Washington Ave Albany, NY 12222', donation: '1500'},
      {id: 292, studentName: 'Emily Fanniff', studentSection: 'Purple', studentGroup: 'Q', donorOrg: '', donorName: 'Samuel Caldwell', donorAddress: '', donation: 'Speaker'},
      {id: 293, studentName: 'Jhamairah Maxwell', studentSection: 'Purple', studentGroup: 'Q', donorOrg: 'Ellenville Elks Lodge 1971', donorName: '', donorAddress: '2 Marconi Drive Latham, NY 12110', donation: '200'},
      {id: 294, studentName: 'Jhamairah Maxwell', studentSection: 'Purple', studentGroup: 'Q', donorOrg: '', donorName: 'Nicholas Francella', donorAddress: '12 Robin Lane Troy, NY 12180', donation: '25'},
      {id: 295, studentName: 'Krista Patel', studentSection: 'Purple', studentGroup: 'Q', donorOrg: 'Stewart\'s', donorName: '', donorAddress: '99 Main St Ravena, NY 12143', donation: 'Purple Section Leader'},
      {id: 296, studentName: 'Krista Patel', studentSection: 'Purple', studentGroup: 'Q', donorOrg: '', donorName: '', donorAddress: '76 North Pearl St, Apt 407 Albany, NY 12207', donation: 'Speaker'},
      {id: 297, studentName: 'Lucas Russell', studentSection: 'Purple', studentGroup: 'Q', donorOrg: 'Kiwanis Club of Troy', donorName: 'Macy Hayes', donorAddress: '95-97 Ferry Street Troy, NY 12180', donation: '225'},
      {id: 298, studentName: 'Lucas Russell', studentSection: 'Purple', studentGroup: 'Q', donorOrg: 'Persico True Value', donorName: 'Jinah Ahn', donorAddress: 'PO Box 307 Chazy, NY 12921- 307', donation: '225'},
      {id: 299, studentName: 'Melania Escobedo', studentSection: 'Purple', studentGroup: 'Q', donorOrg: '', donorName: '', donorAddress: '2212 Route 44 55 Gardiner, NY 12525', donation: 'Speaker'},
      {id: 300, studentName: 'Melania Escobedo', studentSection: 'Purple', studentGroup: 'Q', donorOrg: '', donorName: '', donorAddress: '', donation: '250'},
      {id: 301, studentName: 'Michael Miller', studentSection: 'Purple', studentGroup: 'Q', donorOrg: 'Chazy Lions Club', donorName: 'Ben Williams', donorAddress: '', donation: 'Speaker'},
      {id: 302, studentName: 'Michael Miller', studentSection: 'Purple', studentGroup: 'Q', donorOrg: 'Knights of Columbus #16415', donorName: '', donorAddress: '962 Albany Street Schenectady, NY 12307', donation: 'R Facilitator'},
      {id: 303, studentName: 'Michael Miller', studentSection: 'Purple', studentGroup: 'Q', donorOrg: '', donorName: 'Ashli Fragomeni', donorAddress: '2026 37th St NW Washington, DC 20007', donation: 'Speaker'},
      {id: 304, studentName: 'Olivia Palmer', studentSection: 'Purple', studentGroup: 'Q', donorOrg: 'Thrivent', donorName: 'Benjamin McNutt', donorAddress: '371 Whitehall Rd Albany, NY 12208', donation: 'Purple Section Leader'},
      {id: 305, studentName: 'Olivia Palmer', studentSection: 'Purple', studentGroup: 'Q', donorOrg: '', donorName: 'Brenda Baddam', donorAddress: '76 North Pearl St, Apt 407 Albany, NY 12207', donation: 'Speaker'},
      {id: 306, studentName: 'Cooper Harvey', studentSection: 'Purple', studentGroup: 'R', donorOrg: '', donorName: 'Macy Hayes', donorAddress: '1400 Washington Ave Albany, NY 12222', donation: 'R Facilitator'},
      {id: 307, studentName: 'Cooper Harvey', studentSection: 'Purple', studentGroup: 'R', donorOrg: '', donorName: 'Samuel Caldwell', donorAddress: '2026 37th St NW Washington, DC 20007', donation: 'Speaker'},
      {id: 308, studentName: 'Delana Wood', studentSection: 'Purple', studentGroup: 'R', donorOrg: '', donorName: 'Benjamin McNutt', donorAddress: '1400 Washington Ave Albany, NY 12222', donation: '100'},
      {id: 309, studentName: 'Delana Wood', studentSection: 'Purple', studentGroup: 'R', donorOrg: '', donorName: 'Samuel Caldwell', donorAddress: '501 Fourth Avenue Watervliet, NY 12189', donation: 'Tolietries'},
      {id: 310, studentName: 'Kayla Butler', studentSection: 'Purple', studentGroup: 'R', donorOrg: '', donorName: '', donorAddress: '', donation: '225'},
      {id: 311, studentName: 'Kayla Butler', studentSection: 'Purple', studentGroup: 'R', donorOrg: '', donorName: '', donorAddress: '3867 Carman Road Schenectady, NY 12303-5627', donation: 'Speaker'},
      {id: 312, studentName: 'Kelly Waite', studentSection: 'Purple', studentGroup: 'R', donorOrg: 'Watervliet-Colonie Elks Lodge', donorName: '', donorAddress: '81 Mohawk Street Rear Cohoes, NY 12047', donation: 'S Facilitator'},
      {id: 313, studentName: 'Kelly Waite', studentSection: 'Purple', studentGroup: 'R', donorOrg: 'OraLine', donorName: 'Trent Griffin-Braaf', donorAddress: '116 Congress Street Apt. 2 Cohoes, NY 12047', donation: 'Speaker'},
      {id: 314, studentName: 'Zia Ohene', studentSection: 'Purple', studentGroup: 'R', donorOrg: 'Guilderland Elks 2480', donorName: 'Taylor Bertram', donorAddress: '22 Corporate Woods Blvd, Suite 501 Albany, NY 12211', donation: '1500'},
      {id: 315, studentName: 'Zia Ohene', studentSection: 'Purple', studentGroup: 'R', donorOrg: '', donorName: 'Mara Afzail', donorAddress: '', donation: 'Speaker'},
      {id: 316, studentName: 'Abigail Walkow', studentSection: 'Pink', studentGroup: 'S', donorOrg: '', donorName: '', donorAddress: '962 Albany Street Schenectady, NY 12307', donation: 'S Facilitator'},
      {id: 317, studentName: 'Abigail Walkow', studentSection: 'Pink', studentGroup: 'S', donorOrg: '', donorName: 'Ashli Fragomeni', donorAddress: '116 Congress Street Apt. 2 Cohoes, NY 12047', donation: 'Speaker'},
      {id: 318, studentName: 'Alara Crisafulli', studentSection: 'Pink', studentGroup: 'S', donorOrg: 'Stewart\'s', donorName: 'Taylor Bertram', donorAddress: '371 Whitehall Rd Albany, NY 12208', donation: '200'},
      {id: 319, studentName: 'Alara Crisafulli', studentSection: 'Pink', studentGroup: 'S', donorOrg: '', donorName: 'Brenda Baddam', donorAddress: 'PO Box 446 Slate Hill, NY 10973', donation: 'Speaker'},
      {id: 320, studentName: 'Alexander Remick', studentSection: 'Pink', studentGroup: 'S', donorOrg: '', donorName: '', donorAddress: '4 Century Hill Drive Latham, NY 12110', donation: '225'},
      {id: 321, studentName: 'Alexander Remick', studentSection: 'Pink', studentGroup: 'S', donorOrg: '', donorName: 'LB Hannahs', donorAddress: 'Box 311 Middleburgh, NY 12122', donation: 'Speaker'},
      {id: 322, studentName: 'Braden Nephew', studentSection: 'Pink', studentGroup: 'S', donorOrg: 'Kiwanis Club on Minisink Valley', donorName: '', donorAddress: '2 Marconi Drive Latham, NY 12110', donation: 'Speaker'},
      {id: 323, studentName: 'Braden Nephew', studentSection: 'Pink', studentGroup: 'S', donorOrg: '', donorName: 'Nicholas Francella', donorAddress: '4 Century Hill Drive Latham, NY 12110', donation: '225'},
      {id: 324, studentName: 'Brandon Martinez', studentSection: 'Pink', studentGroup: 'S', donorOrg: 'Knights of Columbus 4475', donorName: 'LB Hannahs', donorAddress: 'PO Box 1100 Middleburgh, NY 12122', donation: '225'},
      {id: 325, studentName: 'Brandon Martinez', studentSection: 'Pink', studentGroup: 'S', donorOrg: '', donorName: '', donorAddress: '1226 State Route 86 Saranac Lake, NY 12983', donation: '2000'},
      {id: 326, studentName: 'Brandon Martinez', studentSection: 'Pink', studentGroup: 'S', donorOrg: '', donorName: '', donorAddress: '384 North Grand Street Cobleskill, NY 12043', donation: 'Speaker'},
      {id: 327, studentName: 'Brooke Devlin', studentSection: 'Pink', studentGroup: 'S', donorOrg: 'Middleburgh Rotary', donorName: '', donorAddress: '962 Albany Street Schenectady, NY 12307', donation: 'I J-Staff'},
      {id: 328, studentName: 'Brooke Devlin', studentSection: 'Pink', studentGroup: 'S', donorOrg: 'Restwork LLC', donorName: 'Ashli Fragomeni', donorAddress: '360 Brand Hollow Rd Plattsburgh, NY 12972', donation: '225'},
      {id: 329, studentName: 'Emma Gallagher', studentSection: 'Pink', studentGroup: 'S', donorOrg: 'Fenimore Assett Management', donorName: 'Destini Bresette', donorAddress: '14 Upper Hillman Rd Warwick, NY 10990-2636', donation: 'R J-Staff'},
      {id: 330, studentName: 'Emma Gallagher', studentSection: 'Pink', studentGroup: 'S', donorOrg: '', donorName: 'Tyler Carey', donorAddress: '134 Cedar Grove Rd Selkirk, NY 12158', donation: 'Speaker'},
      {id: 331, studentName: 'Hannah Ketzer', studentSection: 'Pink', studentGroup: 'S', donorOrg: '', donorName: 'Alyssa Grogan', donorAddress: '95-97 Ferry Street Troy, NY 12180', donation: '2000'},
      {id: 332, studentName: 'Hannah Ketzer', studentSection: 'Pink', studentGroup: 'S', donorOrg: '', donorName: 'Jinah Ahn', donorAddress: '384 North Grand Street Cobleskill, NY 12043', donation: '100'},
      {id: 333, studentName: 'Kearrah Bohley', studentSection: 'Pink', studentGroup: 'S', donorOrg: '', donorName: '', donorAddress: 'Old Station Road Nelliston, NY 13410', donation: 'Speaker'},
      {id: 334, studentName: 'Kearrah Bohley', studentSection: 'Pink', studentGroup: 'S', donorOrg: '', donorName: '', donorAddress: '141 Washington Ave Albany, NY 12210', donation: 'S J-Staff'},
      {id: 335, studentName: 'Slav Mishkovski', studentSection: 'Pink', studentGroup: 'S', donorOrg: 'Fenimore Assett Management', donorName: 'Jahkeen Hoke', donorAddress: '9 Taylor St New Paltz, NY 12561', donation: 'Speaker'},
      {id: 336, studentName: 'Slav Mishkovski', studentSection: 'Pink', studentGroup: 'S', donorOrg: 'Canajoharie F 2621', donorName: 'Dylan Dolan', donorAddress: '2 Marconi Drive Latham, NY 12110', donation: '2000'},
      {id: 337, studentName: 'Slav Mishkovski', studentSection: 'Pink', studentGroup: 'S', donorOrg: '', donorName: 'Nicholas Francella', donorAddress: '384 North Grand Street Cobleskill, NY 12043', donation: 'Speaker'},
      {id: 338, studentName: 'Zadock Favicchio', studentSection: 'Pink', studentGroup: 'S', donorOrg: '', donorName: '', donorAddress: '962 Albany Street Schenectady, NY 12307', donation: 'T Facilitator'},
      {id: 339, studentName: 'Zadock Favicchio', studentSection: 'Pink', studentGroup: 'S', donorOrg: '', donorName: 'Ashli Fragomeni', donorAddress: '173 Patnode Rd West Chazy, NY 12992', donation: 'Speaker'},
      {id: 340, studentName: 'Abigail Dwon', studentSection: 'Pink', studentGroup: 'T', donorOrg: 'Fenimore Assett Management', donorName: 'Cole Denton', donorAddress: '5 Computer Drive S Albany, NY 12205', donation: '100'},
      {id: 341, studentName: 'Abigail Dwon', studentSection: 'Pink', studentGroup: 'T', donorOrg: '', donorName: 'Mark Eagan', donorAddress: '', donation: '26.02'},
      {id: 342, studentName: 'Allison Sayward', studentSection: 'Pink', studentGroup: 'T', donorOrg: '', donorName: 'Matthew Bunten', donorAddress: '2402 Brandywine Parkway Guilderland, NY 20006', donation: 'Speaker'},
      {id: 343, studentName: 'Allison Sayward', studentSection: 'Pink', studentGroup: 'T', donorOrg: '', donorName: 'Courtland Ingraham', donorAddress: '32 Essex Street Albany, NY 12206', donation: '1500'},
      {id: 344, studentName: 'Claire Smith', studentSection: 'Pink', studentGroup: 'T', donorOrg: '', donorName: 'Susan Lintner', donorAddress: '', donation: 'Speaker'},
      {id: 345, studentName: 'Claire Smith', studentSection: 'Pink', studentGroup: 'T', donorOrg: '', donorName: '', donorAddress: '962 Albany Street Schenectady, NY 12307', donation: 'T Facilitator'},
      {id: 346, studentName: 'Claire Smith', studentSection: 'Pink', studentGroup: 'T', donorOrg: '', donorName: 'Ashli Fragomeni', donorAddress: '173 Patnode Rd West Chazy, NY 12992', donation: 'Speaker'},
      {id: 347, studentName: 'Hailey Lamping', studentSection: 'Pink', studentGroup: 'T', donorOrg: 'Stewart\'s', donorName: 'Cole Denton', donorAddress: '200 Green Street Albany, NY 12202', donation: 'L J-Staff'},
      {id: 348, studentName: 'Hailey Lamping', studentSection: 'Pink', studentGroup: 'T', donorOrg: '', donorName: 'Paul "Batman" Collins-Hackett', donorAddress: '64 Elm St. Apt A Peru, NY 12972', donation: 'back packs, floss, water bottles'},
      {id: 349, studentName: 'James Nay', studentSection: 'Pink', studentGroup: 'T', donorOrg: '', donorName: 'Emma Springer', donorAddress: '', donation: '225'},
      {id: 350, studentName: 'James Nay', studentSection: 'Pink', studentGroup: 'T', donorOrg: '', donorName: '', donorAddress: 'PO Box 528 Glens Falls, NY 12801', donation: '100'},
      {id: 351, studentName: 'Katherine Darcy', studentSection: 'Pink', studentGroup: 'T', donorOrg: '', donorName: '', donorAddress: '41 W State St Johnstown, NY 12095', donation: '100'},
      {id: 352, studentName: 'Katherine Darcy', studentSection: 'Pink', studentGroup: 'T', donorOrg: 'Antham', donorName: '', donorAddress: '', donation: '51.74'},
      {id: 353, studentName: 'LexiAnne Kent', studentSection: 'Pink', studentGroup: 'T', donorOrg: 'Glens Falls Lions', donorName: 'Matthew Bunten', donorAddress: '56 Meadow Rue Place Ballston Spa, NY 12020', donation: 'Speaker'},
      {id: 354, studentName: 'LexiAnne Kent', studentSection: 'Pink', studentGroup: 'T', donorOrg: 'Mohan Stop and Shop', donorName: 'Dianne Schwarz', donorAddress: '1 Steuben Place Albany, NY 12207', donation: 'Pink Section Leader'},
      {id: 355, studentName: 'Manyata Madan', studentSection: 'Pink', studentGroup: 'T', donorOrg: '', donorName: 'Angelique Powell', donorAddress: '836 7th Ave Troy, NY 12182', donation: 'Speaker'},
      {id: 356, studentName: 'Manyata Madan', studentSection: 'Pink', studentGroup: 'T', donorOrg: '', donorName: 'Howard Lien', donorAddress: '371 Whitehall Rd Albany, NY 12208', donation: 'U Facilitator'},
      {id: 357, studentName: 'Manyata Madan', studentSection: 'Pink', studentGroup: 'T', donorOrg: '', donorName: 'Brenda Baddam', donorAddress: '410 Maloney Rd Poughkeepsie, NY 12603', donation: 'Speaker'},
      {id: 358, studentName: 'Olivia Hoffman', studentSection: 'Pink', studentGroup: 'T', donorOrg: '', donorName: 'Imani Snipes', donorAddress: '371 Whitehall Rd Albany, NY 12208', donation: 'K J-Staff'},
      {id: 359, studentName: 'Olivia Hoffman', studentSection: 'Pink', studentGroup: 'T', donorOrg: '', donorName: 'Brenda Baddam', donorAddress: '33A Pointe West Dr Clifton Park, NY 12065', donation: '50'},
      {id: 360, studentName: 'Adriana Greyson Soto', studentSection: 'Pink', studentGroup: 'U', donorOrg: '', donorName: 'Alexis Hernaez', donorAddress: '144 Harrison Street Johnstown, NY 12095', donation: 'Q J-Staff'},
      {id: 361, studentName: 'Adriana Greyson Soto', studentSection: 'Pink', studentGroup: 'U', donorOrg: '', donorName: '', donorAddress: '14 Upper Hillman Road Warwick, NY 10990', donation: '50'},
      {id: 362, studentName: 'Alexandra Forte', studentSection: 'Pink', studentGroup: 'U', donorOrg: '', donorName: 'Cricket Carey', donorAddress: '90 Green Street Hudson, NY 12534', donation: 'Pink Section Leader'},
      {id: 363, studentName: 'Alexandra Forte', studentSection: 'Pink', studentGroup: 'U', donorOrg: 'Asante Sign Group', donorName: '', donorAddress: '836 7th Ave Troy, NY 12182', donation: 'Speaker'},
      {id: 364, studentName: 'Ashlyn Burke', studentSection: 'Pink', studentGroup: 'U', donorOrg: '', donorName: 'Howard Lien', donorAddress: '1400 Washington Ave Albany, NY 12222', donation: '500'},
      {id: 365, studentName: 'Ashlyn Burke', studentSection: 'Pink', studentGroup: 'U', donorOrg: 'Since 1914 LLC', donorName: 'Samuel Caldwell', donorAddress: '', donation: '100'},
      {id: 366, studentName: 'Dejah Taylor', studentSection: 'Pink', studentGroup: 'U', donorOrg: '', donorName: '', donorAddress: '41 W State St Johnstown, NY 12095', donation: 'Pink Section Leader'},
      {id: 367, studentName: 'Dejah Taylor', studentSection: 'Pink', studentGroup: 'U', donorOrg: '', donorName: '', donorAddress: '836 7th Ave Troy, NY 12182', donation: 'Speaker'},
      {id: 368, studentName: 'Dylan Slater', studentSection: 'Pink', studentGroup: 'U', donorOrg: 'Bank of Richmondville', donorName: 'Howard Lien', donorAddress: '5 Computer Drive S Albany, NY 12205', donation: 'U Facilitator'},
      {id: 369, studentName: 'Dylan Slater', studentSection: 'Pink', studentGroup: 'U', donorOrg: 'Mohan Stop and Shop', donorName: 'Mark Eagan', donorAddress: '410 Maloney Rd Poughkeepsie, NY 12603', donation: 'Speaker'},
      {id: 370, studentName: 'Michelle Gimena', studentSection: 'Pink', studentGroup: 'U', donorOrg: '', donorName: 'Imani Snipes', donorAddress: '200 Green Street Albany, NY 12202', donation: '100'},
      {id: 371, studentName: 'Michelle Gimena', studentSection: 'Pink', studentGroup: 'U', donorOrg: '', donorName: 'Paul "Batman" Collins-Hackett', donorAddress: '', donation: '103.19'},
      {id: 372, studentName: 'Owen Kapp', studentSection: 'Pink', studentGroup: 'U', donorOrg: '', donorName: 'Matthew Bunten', donorAddress: '', donation: 'Speaker'},
      {id: 373, studentName: 'Owen Kapp', studentSection: 'Pink', studentGroup: 'U', donorOrg: '', donorName: 'Betsy Tromans', donorAddress: '141 Washington Ave Albany, NY 12210', donation: ''},
      {id: 374, studentName: 'Shaya Gerber', studentSection: 'Pink', studentGroup: 'U', donorOrg: '', donorName: 'Jahkeen Hoke', donorAddress: '', donation: ''},
      {id: 375, studentName: 'Shaya Gerber', studentSection: 'Pink', studentGroup: 'U', donorOrg: '', donorName: '', donorAddress: '', donation: ''},
      {id: 376, studentName: 'Shaya Gerber', studentSection: 'Pink', studentGroup: 'U', donorOrg: '', donorName: '', donorAddress: '', donation: ''}
    ]
  }
}
