name: Deploy

on:
  release:
    types:
      - released

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Download latest release
        uses: robinraju/release-downloader@v1.10
        with:
          latest: true
          filename: thank-you-matcher.tar.gz
      - run: |
          tar -xzf thank-you-matcher.tar.gz --directory site
#      - name: Setup Pages
#        uses: actions/configure-pages@v3
#      - name: Upload artifact
#        uses: actions/upload-pages-artifact@v1
#        with:
#          path: 'site/'
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v1
