name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npx ng build --prod
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_push_gpgsign: true
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: "HOBY New York East"
          GIT_AUTHOR_EMAIL: "39279726+hobynye-admin@users.noreply.github.com"
          GIT_COMMITTER_NAME: "HOBY New York East"
          GIT_COMMITTER_EMAIL: "39279726+hobynye-admin@users.noreply.github.com"
        run: npx semantic-release
